// Code generated by mockery. DO NOT EDIT.

package mockconfig

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// GetDatabaseURL provides a mock function with no fields
func (_m *MockManager) GetDatabaseURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockManager_GetDatabaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseURL'
type MockManager_GetDatabaseURL_Call struct {
	*mock.Call
}

// GetDatabaseURL is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetDatabaseURL() *MockManager_GetDatabaseURL_Call {
	return &MockManager_GetDatabaseURL_Call{Call: _e.mock.On("GetDatabaseURL")}
}

func (_c *MockManager_GetDatabaseURL_Call) Run(run func()) *MockManager_GetDatabaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetDatabaseURL_Call) Return(_a0 string) *MockManager_GetDatabaseURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetDatabaseURL_Call) RunAndReturn(run func() string) *MockManager_GetDatabaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbedResourceFolder provides a mock function with no fields
func (_m *MockManager) GetEmbedResourceFolder() fs.FS {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedResourceFolder")
	}

	var r0 fs.FS
	if rf, ok := ret.Get(0).(func() fs.FS); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}

	return r0
}

// MockManager_GetEmbedResourceFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedResourceFolder'
type MockManager_GetEmbedResourceFolder_Call struct {
	*mock.Call
}

// GetEmbedResourceFolder is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetEmbedResourceFolder() *MockManager_GetEmbedResourceFolder_Call {
	return &MockManager_GetEmbedResourceFolder_Call{Call: _e.mock.On("GetEmbedResourceFolder")}
}

func (_c *MockManager_GetEmbedResourceFolder_Call) Run(run func()) *MockManager_GetEmbedResourceFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetEmbedResourceFolder_Call) Return(_a0 fs.FS) *MockManager_GetEmbedResourceFolder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetEmbedResourceFolder_Call) RunAndReturn(run func() fs.FS) *MockManager_GetEmbedResourceFolder_Call {
	_c.Call.Return(run)
	return _c
}

// IsDebugMode provides a mock function with no fields
func (_m *MockManager) IsDebugMode() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDebugMode")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockManager_IsDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDebugMode'
type MockManager_IsDebugMode_Call struct {
	*mock.Call
}

// IsDebugMode is a helper method to define mock.On call
func (_e *MockManager_Expecter) IsDebugMode() *MockManager_IsDebugMode_Call {
	return &MockManager_IsDebugMode_Call{Call: _e.mock.On("IsDebugMode")}
}

func (_c *MockManager_IsDebugMode_Call) Run(run func()) *MockManager_IsDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_IsDebugMode_Call) Return(_a0 bool) *MockManager_IsDebugMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_IsDebugMode_Call) RunAndReturn(run func() bool) *MockManager_IsDebugMode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
