---
name: Snowdrop

volumes:
  postgres-data:

networks:
  backend:

services:
  database:
    container_name: database
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_DB_SUPER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_SUPER_PASSWORD}
      SNOWDROP_DB_NAME: ${SNOWDROP_DB_NAME}
      SNOWDROP_DB_ADMIN_USER: ${SNOWDROP_DB_ADMIN_USER}
      SNOWDROP_DB_ADMIN_PASSWORD: ${SNOWDROP_DB_ADMIN_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.docker/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${SNOWDROP_DB_ADMIN_USER} -d ${SNOWDROP_DB_NAME}"]
      interval: 10s
      retries: 5
      timeout: 10s

  grafana-otel-lgtm:
    image: grafana/otel-lgtm:0.11.1
    restart: always
    networks:
      - backend

  api_console:
    build:
      context: ./backend
      dockerfile: console/Dockerfile
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
        restart: true
      grafana-otel-lgtm:
        condition: service_started
    environment:
      - APP_DB_HOST=${APP_DB_HOST}
      - APP_DB_PORT=${APP_DB_PORT}
      - APP_DB_NAME=${APP_DB_NAME}
      - APP_DB_USERNAME=${APP_DB_USERNAME}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DEFAULT_SYSTEM_PASSWORD=${APP_DEFAULT_SYSTEM_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    healthcheck:
      test: [CMD, curl, -f, http://localhost:3000/healthz]
      interval: 5s
      timeout: 5s
      retries: 3
