// Code generated by mockery. DO NOT EDIT.

package mockdatabase

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgconn "github.com/jackc/pgx/v5/pgconn"

	pgx "github.com/jackc/pgx/v5"

	pgxpool "github.com/jackc/pgx/v5/pgxpool"
)

// MockPool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

type MockPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPool) EXPECT() *MockPool_Expecter {
	return &MockPool_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx
func (_m *MockPool) Acquire(ctx context.Context) (*pgxpool.Conn, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 *pgxpool.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*pgxpool.Conn, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *pgxpool.Conn); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPool_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockPool_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPool_Expecter) Acquire(ctx interface{}) *MockPool_Acquire_Call {
	return &MockPool_Acquire_Call{Call: _e.mock.On("Acquire", ctx)}
}

func (_c *MockPool_Acquire_Call) Run(run func(ctx context.Context)) *MockPool_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPool_Acquire_Call) Return(_a0 *pgxpool.Conn, _a1 error) *MockPool_Acquire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPool_Acquire_Call) RunAndReturn(run func(context.Context) (*pgxpool.Conn, error)) *MockPool_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// AcquireAllIdle provides a mock function with given fields: ctx
func (_m *MockPool) AcquireAllIdle(ctx context.Context) []*pgxpool.Conn {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AcquireAllIdle")
	}

	var r0 []*pgxpool.Conn
	if rf, ok := ret.Get(0).(func(context.Context) []*pgxpool.Conn); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pgxpool.Conn)
		}
	}

	return r0
}

// MockPool_AcquireAllIdle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireAllIdle'
type MockPool_AcquireAllIdle_Call struct {
	*mock.Call
}

// AcquireAllIdle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPool_Expecter) AcquireAllIdle(ctx interface{}) *MockPool_AcquireAllIdle_Call {
	return &MockPool_AcquireAllIdle_Call{Call: _e.mock.On("AcquireAllIdle", ctx)}
}

func (_c *MockPool_AcquireAllIdle_Call) Run(run func(ctx context.Context)) *MockPool_AcquireAllIdle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPool_AcquireAllIdle_Call) Return(_a0 []*pgxpool.Conn) *MockPool_AcquireAllIdle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_AcquireAllIdle_Call) RunAndReturn(run func(context.Context) []*pgxpool.Conn) *MockPool_AcquireAllIdle_Call {
	_c.Call.Return(run)
	return _c
}

// AcquireFunc provides a mock function with given fields: ctx, f
func (_m *MockPool) AcquireFunc(ctx context.Context, f func(*pgxpool.Conn) error) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for AcquireFunc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*pgxpool.Conn) error) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPool_AcquireFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireFunc'
type MockPool_AcquireFunc_Call struct {
	*mock.Call
}

// AcquireFunc is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(*pgxpool.Conn) error
func (_e *MockPool_Expecter) AcquireFunc(ctx interface{}, f interface{}) *MockPool_AcquireFunc_Call {
	return &MockPool_AcquireFunc_Call{Call: _e.mock.On("AcquireFunc", ctx, f)}
}

func (_c *MockPool_AcquireFunc_Call) Run(run func(ctx context.Context, f func(*pgxpool.Conn) error)) *MockPool_AcquireFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(*pgxpool.Conn) error))
	})
	return _c
}

func (_c *MockPool_AcquireFunc_Call) Return(_a0 error) *MockPool_AcquireFunc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_AcquireFunc_Call) RunAndReturn(run func(context.Context, func(*pgxpool.Conn) error) error) *MockPool_AcquireFunc_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function with given fields: ctx
func (_m *MockPool) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPool_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockPool_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPool_Expecter) Begin(ctx interface{}) *MockPool_Begin_Call {
	return &MockPool_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockPool_Begin_Call) Run(run func(ctx context.Context)) *MockPool_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPool_Begin_Call) Return(_a0 pgx.Tx, _a1 error) *MockPool_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPool_Begin_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *MockPool_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function with given fields: ctx, txOptions
func (_m *MockPool) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _m.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return rf(ctx, txOptions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = rf(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = rf(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPool_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockPool_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *MockPool_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *MockPool_BeginTx_Call {
	return &MockPool_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *MockPool_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *MockPool_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.TxOptions))
	})
	return _c
}

func (_c *MockPool_BeginTx_Call) Return(_a0 pgx.Tx, _a1 error) *MockPool_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPool_BeginTx_Call) RunAndReturn(run func(context.Context, pgx.TxOptions) (pgx.Tx, error)) *MockPool_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockPool) Close() {
	_m.Called()
}

// MockPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPool_Expecter) Close() *MockPool_Close_Call {
	return &MockPool_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPool_Close_Call) Run(run func()) *MockPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Close_Call) Return() *MockPool_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPool_Close_Call) RunAndReturn(run func()) *MockPool_Close_Call {
	_c.Run(run)
	return _c
}

// Config provides a mock function with no fields
func (_m *MockPool) Config() *pgxpool.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *pgxpool.Config
	if rf, ok := ret.Get(0).(func() *pgxpool.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Config)
		}
	}

	return r0
}

// MockPool_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockPool_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockPool_Expecter) Config() *MockPool_Config_Call {
	return &MockPool_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockPool_Config_Call) Run(run func()) *MockPool_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Config_Call) Return(_a0 *pgxpool.Config) *MockPool_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_Config_Call) RunAndReturn(run func() *pgxpool.Config) *MockPool_Config_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFrom provides a mock function with given fields: ctx, tableName, columnNames, rowSrc
func (_m *MockPool) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	ret := _m.Called(ctx, tableName, columnNames, rowSrc)

	if len(ret) == 0 {
		panic("no return value specified for CopyFrom")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) (int64, error)); ok {
		return rf(ctx, tableName, columnNames, rowSrc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) int64); ok {
		r0 = rf(ctx, tableName, columnNames, rowSrc)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) error); ok {
		r1 = rf(ctx, tableName, columnNames, rowSrc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPool_CopyFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFrom'
type MockPool_CopyFrom_Call struct {
	*mock.Call
}

// CopyFrom is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName pgx.Identifier
//   - columnNames []string
//   - rowSrc pgx.CopyFromSource
func (_e *MockPool_Expecter) CopyFrom(ctx interface{}, tableName interface{}, columnNames interface{}, rowSrc interface{}) *MockPool_CopyFrom_Call {
	return &MockPool_CopyFrom_Call{Call: _e.mock.On("CopyFrom", ctx, tableName, columnNames, rowSrc)}
}

func (_c *MockPool_CopyFrom_Call) Run(run func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource)) *MockPool_CopyFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Identifier), args[2].([]string), args[3].(pgx.CopyFromSource))
	})
	return _c
}

func (_c *MockPool_CopyFrom_Call) Return(_a0 int64, _a1 error) *MockPool_CopyFrom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPool_CopyFrom_Call) RunAndReturn(run func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) (int64, error)) *MockPool_CopyFrom_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: ctx, sql, arguments
func (_m *MockPool) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, arguments...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return rf(ctx, sql, arguments...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = rf(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...any
func (_e *MockPool_Expecter) Exec(ctx interface{}, sql interface{}, arguments ...interface{}) *MockPool_Exec_Call {
	return &MockPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, arguments...)...)}
}

func (_c *MockPool_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...any)) *MockPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPool_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *MockPool_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPool_Exec_Call) RunAndReturn(run func(context.Context, string, ...any) (pgconn.CommandTag, error)) *MockPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockPool) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPool_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPool_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPool_Expecter) Ping(ctx interface{}) *MockPool_Ping_Call {
	return &MockPool_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockPool_Ping_Call) Run(run func(ctx context.Context)) *MockPool_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPool_Ping_Call) Return(_a0 error) *MockPool_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_Ping_Call) RunAndReturn(run func(context.Context) error) *MockPool_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, sql, args
func (_m *MockPool) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return rf(ctx, sql, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPool_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockPool_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockPool_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_Query_Call {
	return &MockPool_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPool_Query_Call) Return(_a0 pgx.Rows, _a1 error) *MockPool_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPool_Query_Call) RunAndReturn(run func(context.Context, string, ...any) (pgx.Rows, error)) *MockPool_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *MockPool) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// MockPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockPool_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_QueryRow_Call {
	return &MockPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPool_QueryRow_Call) Return(_a0 pgx.Row) *MockPool_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...any) pgx.Row) *MockPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with no fields
func (_m *MockPool) Reset() {
	_m.Called()
}

// MockPool_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockPool_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *MockPool_Expecter) Reset() *MockPool_Reset_Call {
	return &MockPool_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *MockPool_Reset_Call) Run(run func()) *MockPool_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Reset_Call) Return() *MockPool_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPool_Reset_Call) RunAndReturn(run func()) *MockPool_Reset_Call {
	_c.Run(run)
	return _c
}

// SendBatch provides a mock function with given fields: ctx, b
func (_m *MockPool) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 pgx.BatchResults
	if rf, ok := ret.Get(0).(func(context.Context, *pgx.Batch) pgx.BatchResults); ok {
		r0 = rf(ctx, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.BatchResults)
		}
	}

	return r0
}

// MockPool_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type MockPool_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - b *pgx.Batch
func (_e *MockPool_Expecter) SendBatch(ctx interface{}, b interface{}) *MockPool_SendBatch_Call {
	return &MockPool_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, b)}
}

func (_c *MockPool_SendBatch_Call) Run(run func(ctx context.Context, b *pgx.Batch)) *MockPool_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pgx.Batch))
	})
	return _c
}

func (_c *MockPool_SendBatch_Call) Return(_a0 pgx.BatchResults) *MockPool_SendBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_SendBatch_Call) RunAndReturn(run func(context.Context, *pgx.Batch) pgx.BatchResults) *MockPool_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with no fields
func (_m *MockPool) Stat() *pgxpool.Stat {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 *pgxpool.Stat
	if rf, ok := ret.Get(0).(func() *pgxpool.Stat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Stat)
		}
	}

	return r0
}

// MockPool_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockPool_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
func (_e *MockPool_Expecter) Stat() *MockPool_Stat_Call {
	return &MockPool_Stat_Call{Call: _e.mock.On("Stat")}
}

func (_c *MockPool_Stat_Call) Run(run func()) *MockPool_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Stat_Call) Return(_a0 *pgxpool.Stat) *MockPool_Stat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_Stat_Call) RunAndReturn(run func() *pgxpool.Stat) *MockPool_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPool creates a new instance of MockPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPool {
	mock := &MockPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
