// Code generated by mockery. DO NOT EDIT.

package mockdatabase

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockTransactionManager is an autogenerated mock type for the TransactionManager type
type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

// GetCurrentTx provides a mock function with given fields: ctx
func (_m *MockTransactionManager) GetCurrentTx(ctx context.Context) *sql.Tx {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentTx")
	}

	var r0 *sql.Tx
	if rf, ok := ret.Get(0).(func(context.Context) *sql.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	return r0
}

// MockTransactionManager_GetCurrentTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentTx'
type MockTransactionManager_GetCurrentTx_Call struct {
	*mock.Call
}

// GetCurrentTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionManager_Expecter) GetCurrentTx(ctx interface{}) *MockTransactionManager_GetCurrentTx_Call {
	return &MockTransactionManager_GetCurrentTx_Call{Call: _e.mock.On("GetCurrentTx", ctx)}
}

func (_c *MockTransactionManager_GetCurrentTx_Call) Run(run func(ctx context.Context)) *MockTransactionManager_GetCurrentTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransactionManager_GetCurrentTx_Call) Return(_a0 *sql.Tx) *MockTransactionManager_GetCurrentTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionManager_GetCurrentTx_Call) RunAndReturn(run func(context.Context) *sql.Tx) *MockTransactionManager_GetCurrentTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction provides a mock function with given fields: ctx, opts
func (_m *MockTransactionManager) NewTransaction(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for NewTransaction")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionManager_NewTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTransaction'
type MockTransactionManager_NewTransaction_Call struct {
	*mock.Call
}

// NewTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockTransactionManager_Expecter) NewTransaction(ctx interface{}, opts interface{}) *MockTransactionManager_NewTransaction_Call {
	return &MockTransactionManager_NewTransaction_Call{Call: _e.mock.On("NewTransaction", ctx, opts)}
}

func (_c *MockTransactionManager_NewTransaction_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockTransactionManager_NewTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockTransactionManager_NewTransaction_Call) Return(_a0 *sql.Tx, _a1 error) *MockTransactionManager_NewTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionManager_NewTransaction_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockTransactionManager_NewTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionManager creates a new instance of MockTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// NewMockTransactionManager creates and returns a new MockTransactionManager for use in tests.
// It initializes the internal mock using the provided testing interface and registers a cleanup callback
// to assert that all expected interactions occurred when the test concludes.
func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
