// Code generated by mockery. DO NOT EDIT.

package mockdatabase

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockTxDataFunc is an autogenerated mock type for the TxDataFunc type
type MockTxDataFunc[T any] struct {
	mock.Mock
}

type MockTxDataFunc_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockTxDataFunc[T]) EXPECT() *MockTxDataFunc_Expecter[T] {
	return &MockTxDataFunc_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, tx
func (_m *MockTxDataFunc[T]) Execute(ctx context.Context, tx *sql.Tx) (T, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx) (T, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx) T); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxDataFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTxDataFunc_Execute_Call[T any] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
func (_e *MockTxDataFunc_Expecter[T]) Execute(ctx interface{}, tx interface{}) *MockTxDataFunc_Execute_Call[T] {
	return &MockTxDataFunc_Execute_Call[T]{Call: _e.mock.On("Execute", ctx, tx)}
}

func (_c *MockTxDataFunc_Execute_Call[T]) Run(run func(ctx context.Context, tx *sql.Tx)) *MockTxDataFunc_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx))
	})
	return _c
}

func (_c *MockTxDataFunc_Execute_Call[T]) Return(_a0 T, _a1 error) *MockTxDataFunc_Execute_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTxDataFunc_Execute_Call[T]) RunAndReturn(run func(context.Context, *sql.Tx) (T, error)) *MockTxDataFunc_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockTxDataFunc creates a new instance of MockTxDataFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxDataFunc[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxDataFunc[T] {
	mock := &MockTxDataFunc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
