// Code generated by mockery. DO NOT EDIT.

package mockdatabase

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockTxFunc is an autogenerated mock type for the TxFunc type
type MockTxFunc struct {
	mock.Mock
}

type MockTxFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxFunc) EXPECT() *MockTxFunc_Expecter {
	return &MockTxFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, tx
func (_m *MockTxFunc) Execute(ctx context.Context, tx *sql.Tx) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTxFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
func (_e *MockTxFunc_Expecter) Execute(ctx interface{}, tx interface{}) *MockTxFunc_Execute_Call {
	return &MockTxFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, tx)}
}

func (_c *MockTxFunc_Execute_Call) Run(run func(ctx context.Context, tx *sql.Tx)) *MockTxFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx))
	})
	return _c
}

func (_c *MockTxFunc_Execute_Call) Return(_a0 error) *MockTxFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxFunc_Execute_Call) RunAndReturn(run func(context.Context, *sql.Tx) error) *MockTxFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxFunc creates a new instance of MockTxFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// NewMockTxFunc creates a new MockTxFunc instance and sets up automatic verification of its expectations.
// It accepts a testing interface (typically a *testing.T) and registers a cleanup callback to assert that
// all expected calls on the mock are fulfilled once the test completes.
func NewMockTxFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxFunc {
	mock := &MockTxFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
