---
version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - funcorder
    - tagalign
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    # Replaced by revive.cognitive-complexity
    # - cyclop
    - decorder
    - dupl
    - durationcheck
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    # Replaced by revive.cognitive-complexity
    # - gocognit
    - goconst
    - gocritic
    # Replaced by revive.cognitive-complexity
    # - gocyclo
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - ireturn
    # Replaced by revive.line-length-limit
    # - lll
    - makezero
    - mirror
    # - mnd
    - musttag
    - nakedret
    # Replaced by revive.max-control-nesting
    # - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl
    - err113
    - exptostd
    - forcetypeassert
    - gochecknoglobals
    - iface
    - inamedparam
    - interfacebloat
    # - maintidx
    - misspell
    - nilnesserr
    - nlreturn
    - paralleltest
    - recvcheck
    # - wrapcheck
    - contextcheck
  settings:
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
      allowed-errors: []
      allowed-errors-wildcard: []
    funcorder:
      constructor: true
      struct-method: true
    gosec:
      includes: []
      excludes: []
      severity: low
      confidence: low
    usestdlibvars:
      http-method: true
      http-status-code: true
    testifylint:
      enable-all: true
    tagalign:
      strict: true
      align: true
      sort: true
      order:
        - json
        - yaml
        - yml
        - toml
        - mapstructure
        - binding
        - validate
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
      disable-dec-num-check: true
      disable-type-dec-num-check: true
      disable-const-dec-num-check: true
      disable-var-dec-num-check: true
      disable-dec-order-check: false
      disable-init-func-first-check: true
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gomoddirectives:
      replace-local: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    ireturn:
      allow:
        - empty
        - error
        - stdlib
        - anon
        - generic
        - fx.Option
        - universal-translator.Translator
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - ireturn
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: true
      no-global: all
      context: scope
      msg-style: lowercased
      no-raw-keys: true
      key-naming-case: kebab
      forbidden-keys:
        - time
        - level
        - source
        - msg
      args-on-sep-lines: true
    staticcheck:
      checks:
        - all
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          arguments: [4]
        - name: line-length-limit
          arguments: [120]
        - name: filename-format
          disabled: true
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-zA-Z0-9]{0,}$
        - name: cognitive-complexity
          arguments: [15]
        - name: max-control-nesting
          arguments: [3]
        - name: function-result-limit
          arguments: [2]
    perfsprint:
      integer-format: true
      int-conversion: true
      error-format: true
      err-error: true
      errorf: true
      string-format: true
      sprintf1: true
      strconcat: true
      bool-format: true
      hex-format: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    golines:
      # Same with revive.line-length-limit
      max-len: 120
      reformat-tags: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true
