---
all: true
dir: mocks/{{.SrcPackagePath}}
filename: mocks.go
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: mock{{.SrcPackageName}}
recursive: true
template: testify
packages:
  internal.snowdrop/common:
  internal.snowdrop/framework:
