---
dir: mocks/{{.PackagePath}}
mockname: "{{.Mock}}{{.InterfaceName}}"
outpkg: mock{{.PackageName}}
filename: "{{.InterfaceName}}.go"
all: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
recursive: true
disable-func-mocks: true
packages:
  internal.snowdrop/common:
  internal.snowdrop/framework:
