// Code generated by mockery. DO NOT EDIT.

package mocksession

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	store "internal.snowdrop/common/store"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, userID, expiresAt
func (_m *MockRepository) CreateSession(ctx context.Context, userID uuid.UUID, expiresAt time.Time) (*store.SessionModel, error) {
	ret := _m.Called(ctx, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *store.SessionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (*store.SessionModel, error)); ok {
		return rf(ctx, userID, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) *store.SessionModel); ok {
		r0 = rf(ctx, userID, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.SessionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - expiresAt time.Time
func (_e *MockRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, expiresAt interface{}) *MockRepository_CreateSession_Call {
	return &MockRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, expiresAt)}
}

func (_c *MockRepository_CreateSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, expiresAt time.Time)) *MockRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CreateSession_Call) Return(_a0 *store.SessionModel, _a1 error) *MockRepository_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (*store.SessionModel, error)) *MockRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredSessions provides a mock function with given fields: ctx
func (_m *MockRepository) DeleteExpiredSessions(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredSessions'
type MockRepository_DeleteExpiredSessions_Call struct {
	*mock.Call
}

// DeleteExpiredSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) DeleteExpiredSessions(ctx interface{}) *MockRepository_DeleteExpiredSessions_Call {
	return &MockRepository_DeleteExpiredSessions_Call{Call: _e.mock.On("DeleteExpiredSessions", ctx)}
}

func (_c *MockRepository_DeleteExpiredSessions_Call) Run(run func(ctx context.Context)) *MockRepository_DeleteExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_DeleteExpiredSessions_Call) Return(_a0 error) *MockRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteExpiredSessions_Call) RunAndReturn(run func(context.Context) error) *MockRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, sessionID
func (_m *MockRepository) DeleteSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockRepository_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockRepository_DeleteSession_Call {
	return &MockRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockRepository_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteSession_Call) Return(_a0 error) *MockRepository_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteSession_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, sessionID
func (_m *MockRepository) GetSession(ctx context.Context, sessionID string) (*store.SessionModel, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *store.SessionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.SessionModel, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.SessionModel); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.SessionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockRepository_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockRepository_GetSession_Call {
	return &MockRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockRepository_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSession_Call) Return(_a0 *store.SessionModel, _a1 error) *MockRepository_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSession_Call) RunAndReturn(run func(context.Context, string) (*store.SessionModel, error)) *MockRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function with given fields: ctx, sessionID, lastAccessedAt, expiresAt
func (_m *MockRepository) UpdateSession(ctx context.Context, sessionID string, lastAccessedAt time.Time, expiresAt time.Time) error {
	ret := _m.Called(ctx, sessionID, lastAccessedAt, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, sessionID, lastAccessedAt, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type MockRepository_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - lastAccessedAt time.Time
//   - expiresAt time.Time
func (_e *MockRepository_Expecter) UpdateSession(ctx interface{}, sessionID interface{}, lastAccessedAt interface{}, expiresAt interface{}) *MockRepository_UpdateSession_Call {
	return &MockRepository_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, sessionID, lastAccessedAt, expiresAt)}
}

func (_c *MockRepository_UpdateSession_Call) Run(run func(ctx context.Context, sessionID string, lastAccessedAt time.Time, expiresAt time.Time)) *MockRepository_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_UpdateSession_Call) Return(_a0 error) *MockRepository_UpdateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateSession_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) error) *MockRepository_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
