// Code generated by mockery. DO NOT EDIT.

package mocksnowdrop

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
	language "golang.org/x/text/language"
)

// MockConfigManager is an autogenerated mock type for the ConfigManager type
type MockConfigManager struct {
	mock.Mock
}

type MockConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigManager) EXPECT() *MockConfigManager_Expecter {
	return &MockConfigManager_Expecter{mock: &_m.Mock}
}

// GetAppPort provides a mock function with no fields
func (_m *MockConfigManager) GetAppPort() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppPort")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigManager_GetAppPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppPort'
type MockConfigManager_GetAppPort_Call struct {
	*mock.Call
}

// GetAppPort is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetAppPort() *MockConfigManager_GetAppPort_Call {
	return &MockConfigManager_GetAppPort_Call{Call: _e.mock.On("GetAppPort")}
}

func (_c *MockConfigManager_GetAppPort_Call) Run(run func()) *MockConfigManager_GetAppPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetAppPort_Call) Return(_a0 string) *MockConfigManager_GetAppPort_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigManager_GetAppPort_Call) RunAndReturn(run func() string) *MockConfigManager_GetAppPort_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppRevision provides a mock function with no fields
func (_m *MockConfigManager) GetAppRevision() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppRevision")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigManager_GetAppRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppRevision'
type MockConfigManager_GetAppRevision_Call struct {
	*mock.Call
}

// GetAppRevision is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetAppRevision() *MockConfigManager_GetAppRevision_Call {
	return &MockConfigManager_GetAppRevision_Call{Call: _e.mock.On("GetAppRevision")}
}

func (_c *MockConfigManager_GetAppRevision_Call) Run(run func()) *MockConfigManager_GetAppRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetAppRevision_Call) Return(_a0 string) *MockConfigManager_GetAppRevision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigManager_GetAppRevision_Call) RunAndReturn(run func() string) *MockConfigManager_GetAppRevision_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppVersion provides a mock function with no fields
func (_m *MockConfigManager) GetAppVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigManager_GetAppVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppVersion'
type MockConfigManager_GetAppVersion_Call struct {
	*mock.Call
}

// GetAppVersion is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetAppVersion() *MockConfigManager_GetAppVersion_Call {
	return &MockConfigManager_GetAppVersion_Call{Call: _e.mock.On("GetAppVersion")}
}

func (_c *MockConfigManager_GetAppVersion_Call) Run(run func()) *MockConfigManager_GetAppVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetAppVersion_Call) Return(_a0 string) *MockConfigManager_GetAppVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigManager_GetAppVersion_Call) RunAndReturn(run func() string) *MockConfigManager_GetAppVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseURL provides a mock function with no fields
func (_m *MockConfigManager) GetDatabaseURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigManager_GetDatabaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseURL'
type MockConfigManager_GetDatabaseURL_Call struct {
	*mock.Call
}

// GetDatabaseURL is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetDatabaseURL() *MockConfigManager_GetDatabaseURL_Call {
	return &MockConfigManager_GetDatabaseURL_Call{Call: _e.mock.On("GetDatabaseURL")}
}

func (_c *MockConfigManager_GetDatabaseURL_Call) Run(run func()) *MockConfigManager_GetDatabaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetDatabaseURL_Call) Return(_a0 string) *MockConfigManager_GetDatabaseURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigManager_GetDatabaseURL_Call) RunAndReturn(run func() string) *MockConfigManager_GetDatabaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbedResourceFolder provides a mock function with no fields
func (_m *MockConfigManager) GetEmbedResourceFolder() fs.FS {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedResourceFolder")
	}

	var r0 fs.FS
	if rf, ok := ret.Get(0).(func() fs.FS); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}

	return r0
}

// MockConfigManager_GetEmbedResourceFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedResourceFolder'
type MockConfigManager_GetEmbedResourceFolder_Call struct {
	*mock.Call
}

// GetEmbedResourceFolder is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetEmbedResourceFolder() *MockConfigManager_GetEmbedResourceFolder_Call {
	return &MockConfigManager_GetEmbedResourceFolder_Call{Call: _e.mock.On("GetEmbedResourceFolder")}
}

func (_c *MockConfigManager_GetEmbedResourceFolder_Call) Run(run func()) *MockConfigManager_GetEmbedResourceFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetEmbedResourceFolder_Call) Return(_a0 fs.FS) *MockConfigManager_GetEmbedResourceFolder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigManager_GetEmbedResourceFolder_Call) RunAndReturn(run func() fs.FS) *MockConfigManager_GetEmbedResourceFolder_Call {
	_c.Call.Return(run)
	return _c
}

// GetSupportedLanguages provides a mock function with no fields
func (_m *MockConfigManager) GetSupportedLanguages() []language.Tag {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSupportedLanguages")
	}

	var r0 []language.Tag
	if rf, ok := ret.Get(0).(func() []language.Tag); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]language.Tag)
		}
	}

	return r0
}

// MockConfigManager_GetSupportedLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupportedLanguages'
type MockConfigManager_GetSupportedLanguages_Call struct {
	*mock.Call
}

// GetSupportedLanguages is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetSupportedLanguages() *MockConfigManager_GetSupportedLanguages_Call {
	return &MockConfigManager_GetSupportedLanguages_Call{Call: _e.mock.On("GetSupportedLanguages")}
}

func (_c *MockConfigManager_GetSupportedLanguages_Call) Run(run func()) *MockConfigManager_GetSupportedLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetSupportedLanguages_Call) Return(_a0 []language.Tag) *MockConfigManager_GetSupportedLanguages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigManager_GetSupportedLanguages_Call) RunAndReturn(run func() []language.Tag) *MockConfigManager_GetSupportedLanguages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigManager creates a new instance of MockConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigManager {
	mock := &MockConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
