// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksnowdrop

import (
	"context"
	"database/sql"
	"io/fs"
	"net/http"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/text/language"
	"internal.snowdrop/framework"
)

// NewMockConfigManager creates a new instance of MockConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigManager {
	mock := &MockConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigManager is an autogenerated mock type for the ConfigManager type
type MockConfigManager struct {
	mock.Mock
}

type MockConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigManager) EXPECT() *MockConfigManager_Expecter {
	return &MockConfigManager_Expecter{mock: &_m.Mock}
}

// GetAppPort provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetAppPort() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppPort")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigManager_GetAppPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppPort'
type MockConfigManager_GetAppPort_Call struct {
	*mock.Call
}

// GetAppPort is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetAppPort() *MockConfigManager_GetAppPort_Call {
	return &MockConfigManager_GetAppPort_Call{Call: _e.mock.On("GetAppPort")}
}

func (_c *MockConfigManager_GetAppPort_Call) Run(run func()) *MockConfigManager_GetAppPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetAppPort_Call) Return(s string) *MockConfigManager_GetAppPort_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigManager_GetAppPort_Call) RunAndReturn(run func() string) *MockConfigManager_GetAppPort_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppRevision provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetAppRevision() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppRevision")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigManager_GetAppRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppRevision'
type MockConfigManager_GetAppRevision_Call struct {
	*mock.Call
}

// GetAppRevision is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetAppRevision() *MockConfigManager_GetAppRevision_Call {
	return &MockConfigManager_GetAppRevision_Call{Call: _e.mock.On("GetAppRevision")}
}

func (_c *MockConfigManager_GetAppRevision_Call) Run(run func()) *MockConfigManager_GetAppRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetAppRevision_Call) Return(s string) *MockConfigManager_GetAppRevision_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigManager_GetAppRevision_Call) RunAndReturn(run func() string) *MockConfigManager_GetAppRevision_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppVersion provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetAppVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigManager_GetAppVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppVersion'
type MockConfigManager_GetAppVersion_Call struct {
	*mock.Call
}

// GetAppVersion is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetAppVersion() *MockConfigManager_GetAppVersion_Call {
	return &MockConfigManager_GetAppVersion_Call{Call: _e.mock.On("GetAppVersion")}
}

func (_c *MockConfigManager_GetAppVersion_Call) Run(run func()) *MockConfigManager_GetAppVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetAppVersion_Call) Return(s string) *MockConfigManager_GetAppVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigManager_GetAppVersion_Call) RunAndReturn(run func() string) *MockConfigManager_GetAppVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseURL provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetDatabaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigManager_GetDatabaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseURL'
type MockConfigManager_GetDatabaseURL_Call struct {
	*mock.Call
}

// GetDatabaseURL is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetDatabaseURL() *MockConfigManager_GetDatabaseURL_Call {
	return &MockConfigManager_GetDatabaseURL_Call{Call: _e.mock.On("GetDatabaseURL")}
}

func (_c *MockConfigManager_GetDatabaseURL_Call) Run(run func()) *MockConfigManager_GetDatabaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetDatabaseURL_Call) Return(s string) *MockConfigManager_GetDatabaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigManager_GetDatabaseURL_Call) RunAndReturn(run func() string) *MockConfigManager_GetDatabaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbedResourceFolder provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetEmbedResourceFolder() fs.FS {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedResourceFolder")
	}

	var r0 fs.FS
	if returnFunc, ok := ret.Get(0).(func() fs.FS); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}
	return r0
}

// MockConfigManager_GetEmbedResourceFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedResourceFolder'
type MockConfigManager_GetEmbedResourceFolder_Call struct {
	*mock.Call
}

// GetEmbedResourceFolder is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetEmbedResourceFolder() *MockConfigManager_GetEmbedResourceFolder_Call {
	return &MockConfigManager_GetEmbedResourceFolder_Call{Call: _e.mock.On("GetEmbedResourceFolder")}
}

func (_c *MockConfigManager_GetEmbedResourceFolder_Call) Run(run func()) *MockConfigManager_GetEmbedResourceFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetEmbedResourceFolder_Call) Return(fS fs.FS) *MockConfigManager_GetEmbedResourceFolder_Call {
	_c.Call.Return(fS)
	return _c
}

func (_c *MockConfigManager_GetEmbedResourceFolder_Call) RunAndReturn(run func() fs.FS) *MockConfigManager_GetEmbedResourceFolder_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxRequestSize provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetMaxRequestSize() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxRequestSize")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockConfigManager_GetMaxRequestSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxRequestSize'
type MockConfigManager_GetMaxRequestSize_Call struct {
	*mock.Call
}

// GetMaxRequestSize is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetMaxRequestSize() *MockConfigManager_GetMaxRequestSize_Call {
	return &MockConfigManager_GetMaxRequestSize_Call{Call: _e.mock.On("GetMaxRequestSize")}
}

func (_c *MockConfigManager_GetMaxRequestSize_Call) Run(run func()) *MockConfigManager_GetMaxRequestSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetMaxRequestSize_Call) Return(n int64) *MockConfigManager_GetMaxRequestSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockConfigManager_GetMaxRequestSize_Call) RunAndReturn(run func() int64) *MockConfigManager_GetMaxRequestSize_Call {
	_c.Call.Return(run)
	return _c
}

// GetSupportedLanguages provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetSupportedLanguages() []language.Tag {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSupportedLanguages")
	}

	var r0 []language.Tag
	if returnFunc, ok := ret.Get(0).(func() []language.Tag); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]language.Tag)
		}
	}
	return r0
}

// MockConfigManager_GetSupportedLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupportedLanguages'
type MockConfigManager_GetSupportedLanguages_Call struct {
	*mock.Call
}

// GetSupportedLanguages is a helper method to define mock.On call
func (_e *MockConfigManager_Expecter) GetSupportedLanguages() *MockConfigManager_GetSupportedLanguages_Call {
	return &MockConfigManager_GetSupportedLanguages_Call{Call: _e.mock.On("GetSupportedLanguages")}
}

func (_c *MockConfigManager_GetSupportedLanguages_Call) Run(run func()) *MockConfigManager_GetSupportedLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigManager_GetSupportedLanguages_Call) Return(tags []language.Tag) *MockConfigManager_GetSupportedLanguages_Call {
	_c.Call.Return(tags)
	return _c
}

func (_c *MockConfigManager_GetSupportedLanguages_Call) RunAndReturn(run func() []language.Tag) *MockConfigManager_GetSupportedLanguages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionManager creates a new instance of MockTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionManager is an autogenerated mock type for the TransactionManager type
type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

// GetCurrentTx provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) GetCurrentTx(ctx context.Context) *sql.Tx {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentTx")
	}

	var r0 *sql.Tx
	if returnFunc, ok := ret.Get(0).(func(context.Context) *sql.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}
	return r0
}

// MockTransactionManager_GetCurrentTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentTx'
type MockTransactionManager_GetCurrentTx_Call struct {
	*mock.Call
}

// GetCurrentTx is a helper method to define mock.On call
//   - ctx
func (_e *MockTransactionManager_Expecter) GetCurrentTx(ctx interface{}) *MockTransactionManager_GetCurrentTx_Call {
	return &MockTransactionManager_GetCurrentTx_Call{Call: _e.mock.On("GetCurrentTx", ctx)}
}

func (_c *MockTransactionManager_GetCurrentTx_Call) Run(run func(ctx context.Context)) *MockTransactionManager_GetCurrentTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransactionManager_GetCurrentTx_Call) Return(tx *sql.Tx) *MockTransactionManager_GetCurrentTx_Call {
	_c.Call.Return(tx)
	return _c
}

func (_c *MockTransactionManager_GetCurrentTx_Call) RunAndReturn(run func(ctx context.Context) *sql.Tx) *MockTransactionManager_GetCurrentTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) NewTransaction(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for NewTransaction")
	}

	var r0 *sql.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionManager_NewTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTransaction'
type MockTransactionManager_NewTransaction_Call struct {
	*mock.Call
}

// NewTransaction is a helper method to define mock.On call
//   - ctx
//   - opts
func (_e *MockTransactionManager_Expecter) NewTransaction(ctx interface{}, opts interface{}) *MockTransactionManager_NewTransaction_Call {
	return &MockTransactionManager_NewTransaction_Call{Call: _e.mock.On("NewTransaction", ctx, opts)}
}

func (_c *MockTransactionManager_NewTransaction_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockTransactionManager_NewTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockTransactionManager_NewTransaction_Call) Return(tx *sql.Tx, err error) *MockTransactionManager_NewTransaction_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockTransactionManager_NewTransaction_Call) RunAndReturn(run func(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error)) *MockTransactionManager_NewTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPHandler creates a new instance of MockHTTPHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPHandler {
	mock := &MockHTTPHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPHandler is an autogenerated mock type for the HTTPHandler type
type MockHTTPHandler struct {
	mock.Mock
}

type MockHTTPHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPHandler) EXPECT() *MockHTTPHandler_Expecter {
	return &MockHTTPHandler_Expecter{mock: &_m.Mock}
}

// Method provides a mock function for the type MockHTTPHandler
func (_mock *MockHTTPHandler) Method() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockHTTPHandler_Method_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Method'
type MockHTTPHandler_Method_Call struct {
	*mock.Call
}

// Method is a helper method to define mock.On call
func (_e *MockHTTPHandler_Expecter) Method() *MockHTTPHandler_Method_Call {
	return &MockHTTPHandler_Method_Call{Call: _e.mock.On("Method")}
}

func (_c *MockHTTPHandler_Method_Call) Run(run func()) *MockHTTPHandler_Method_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPHandler_Method_Call) Return(s string) *MockHTTPHandler_Method_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockHTTPHandler_Method_Call) RunAndReturn(run func() string) *MockHTTPHandler_Method_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type MockHTTPHandler
func (_mock *MockHTTPHandler) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockHTTPHandler_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockHTTPHandler_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockHTTPHandler_Expecter) Path() *MockHTTPHandler_Path_Call {
	return &MockHTTPHandler_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockHTTPHandler_Path_Call) Run(run func()) *MockHTTPHandler_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPHandler_Path_Call) Return(s string) *MockHTTPHandler_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockHTTPHandler_Path_Call) RunAndReturn(run func() string) *MockHTTPHandler_Path_Call {
	_c.Call.Return(run)
	return _c
}

// ServeHTTP provides a mock function for the type MockHTTPHandler
func (_mock *MockHTTPHandler) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockHTTPHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockHTTPHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter
//   - request
func (_e *MockHTTPHandler_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *MockHTTPHandler_ServeHTTP_Call {
	return &MockHTTPHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *MockHTTPHandler_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHTTPHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockHTTPHandler_ServeHTTP_Call) Return() *MockHTTPHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPHandler_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHTTPHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}

// Tags provides a mock function for the type MockHTTPHandler
func (_mock *MockHTTPHandler) Tags() []snowdrop.RouteTag {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 []snowdrop.RouteTag
	if returnFunc, ok := ret.Get(0).(func() []snowdrop.RouteTag); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]snowdrop.RouteTag)
		}
	}
	return r0
}

// MockHTTPHandler_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type MockHTTPHandler_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
func (_e *MockHTTPHandler_Expecter) Tags() *MockHTTPHandler_Tags_Call {
	return &MockHTTPHandler_Tags_Call{Call: _e.mock.On("Tags")}
}

func (_c *MockHTTPHandler_Tags_Call) Run(run func()) *MockHTTPHandler_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPHandler_Tags_Call) Return(vs []snowdrop.RouteTag) *MockHTTPHandler_Tags_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *MockHTTPHandler_Tags_Call) RunAndReturn(run func() []snowdrop.RouteTag) *MockHTTPHandler_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionManager creates a new instance of MockSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionManager {
	mock := &MockSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionManager is an autogenerated mock type for the SessionManager type
type MockSessionManager struct {
	mock.Mock
}

type MockSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionManager) EXPECT() *MockSessionManager_Expecter {
	return &MockSessionManager_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) CreateSession(ctx context.Context, userID uuid.UUID, data map[string]any) (*snowdrop.SessionModel, error) {
	ret := _mock.Called(ctx, userID, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *snowdrop.SessionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) (*snowdrop.SessionModel, error)); ok {
		return returnFunc(ctx, userID, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) *snowdrop.SessionModel); ok {
		r0 = returnFunc(ctx, userID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowdrop.SessionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any) error); ok {
		r1 = returnFunc(ctx, userID, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionManager_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionManager_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx
//   - userID
//   - data
func (_e *MockSessionManager_Expecter) CreateSession(ctx interface{}, userID interface{}, data interface{}) *MockSessionManager_CreateSession_Call {
	return &MockSessionManager_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, data)}
}

func (_c *MockSessionManager_CreateSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, data map[string]any)) *MockSessionManager_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(map[string]any))
	})
	return _c
}

func (_c *MockSessionManager_CreateSession_Call) Return(sessionModel *snowdrop.SessionModel, err error) *MockSessionManager_CreateSession_Call {
	_c.Call.Return(sessionModel, err)
	return _c
}

func (_c *MockSessionManager_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, data map[string]any) (*snowdrop.SessionModel, error)) *MockSessionManager_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DestroySession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) DestroySession(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DestroySession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionManager_DestroySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroySession'
type MockSessionManager_DestroySession_Call struct {
	*mock.Call
}

// DestroySession is a helper method to define mock.On call
//   - ctx
//   - sessionID
func (_e *MockSessionManager_Expecter) DestroySession(ctx interface{}, sessionID interface{}) *MockSessionManager_DestroySession_Call {
	return &MockSessionManager_DestroySession_Call{Call: _e.mock.On("DestroySession", ctx, sessionID)}
}

func (_c *MockSessionManager_DestroySession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionManager_DestroySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionManager_DestroySession_Call) Return(err error) *MockSessionManager_DestroySession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionManager_DestroySession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockSessionManager_DestroySession_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) GetConfig() snowdrop.SessionConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 snowdrop.SessionConfig
	if returnFunc, ok := ret.Get(0).(func() snowdrop.SessionConfig); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(snowdrop.SessionConfig)
	}
	return r0
}

// MockSessionManager_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockSessionManager_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockSessionManager_Expecter) GetConfig() *MockSessionManager_GetConfig_Call {
	return &MockSessionManager_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockSessionManager_GetConfig_Call) Run(run func()) *MockSessionManager_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionManager_GetConfig_Call) Return(sessionConfig snowdrop.SessionConfig) *MockSessionManager_GetConfig_Call {
	_c.Call.Return(sessionConfig)
	return _c
}

func (_c *MockSessionManager_GetConfig_Call) RunAndReturn(run func() snowdrop.SessionConfig) *MockSessionManager_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) GetSession(ctx context.Context, sessionID string) (*snowdrop.SessionModel, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *snowdrop.SessionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snowdrop.SessionModel, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snowdrop.SessionModel); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowdrop.SessionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionManager_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionManager_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx
//   - sessionID
func (_e *MockSessionManager_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockSessionManager_GetSession_Call {
	return &MockSessionManager_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockSessionManager_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionManager_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionManager_GetSession_Call) Return(sessionModel *snowdrop.SessionModel, err error) *MockSessionManager_GetSession_Call {
	_c.Call.Return(sessionModel, err)
	return _c
}

func (_c *MockSessionManager_GetSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*snowdrop.SessionModel, error)) *MockSessionManager_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionIDFromCookie provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) GetSessionIDFromCookie(r *http.Request) (*string, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionIDFromCookie")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*string, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *string); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionManager_GetSessionIDFromCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionIDFromCookie'
type MockSessionManager_GetSessionIDFromCookie_Call struct {
	*mock.Call
}

// GetSessionIDFromCookie is a helper method to define mock.On call
//   - r
func (_e *MockSessionManager_Expecter) GetSessionIDFromCookie(r interface{}) *MockSessionManager_GetSessionIDFromCookie_Call {
	return &MockSessionManager_GetSessionIDFromCookie_Call{Call: _e.mock.On("GetSessionIDFromCookie", r)}
}

func (_c *MockSessionManager_GetSessionIDFromCookie_Call) Run(run func(r *http.Request)) *MockSessionManager_GetSessionIDFromCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockSessionManager_GetSessionIDFromCookie_Call) Return(s *string, err error) *MockSessionManager_GetSessionIDFromCookie_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSessionManager_GetSessionIDFromCookie_Call) RunAndReturn(run func(r *http.Request) (*string, error)) *MockSessionManager_GetSessionIDFromCookie_Call {
	_c.Call.Return(run)
	return _c
}

// UpgradeSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) UpgradeSession(w http.ResponseWriter, r *http.Request, userID uuid.UUID) (*snowdrop.SessionModel, error) {
	ret := _mock.Called(w, r, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpgradeSession")
	}

	var r0 *snowdrop.SessionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, uuid.UUID) (*snowdrop.SessionModel, error)); ok {
		return returnFunc(w, r, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, uuid.UUID) *snowdrop.SessionModel); ok {
		r0 = returnFunc(w, r, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowdrop.SessionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request, uuid.UUID) error); ok {
		r1 = returnFunc(w, r, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionManager_UpgradeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpgradeSession'
type MockSessionManager_UpgradeSession_Call struct {
	*mock.Call
}

// UpgradeSession is a helper method to define mock.On call
//   - w
//   - r
//   - userID
func (_e *MockSessionManager_Expecter) UpgradeSession(w interface{}, r interface{}, userID interface{}) *MockSessionManager_UpgradeSession_Call {
	return &MockSessionManager_UpgradeSession_Call{Call: _e.mock.On("UpgradeSession", w, r, userID)}
}

func (_c *MockSessionManager_UpgradeSession_Call) Run(run func(w http.ResponseWriter, r *http.Request, userID uuid.UUID)) *MockSessionManager_UpgradeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionManager_UpgradeSession_Call) Return(sessionModel *snowdrop.SessionModel, err error) *MockSessionManager_UpgradeSession_Call {
	_c.Call.Return(sessionModel, err)
	return _c
}

func (_c *MockSessionManager_UpgradeSession_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, userID uuid.UUID) (*snowdrop.SessionModel, error)) *MockSessionManager_UpgradeSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) CreateSession(ctx context.Context, userID uuid.UUID, data map[string]any, expiresAt time.Time) (*snowdrop.SessionModel, error) {
	ret := _mock.Called(ctx, userID, data, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *snowdrop.SessionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, time.Time) (*snowdrop.SessionModel, error)); ok {
		return returnFunc(ctx, userID, data, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, time.Time) *snowdrop.SessionModel); ok {
		r0 = returnFunc(ctx, userID, data, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowdrop.SessionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, data, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx
//   - userID
//   - data
//   - expiresAt
func (_e *MockSessionRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, data interface{}, expiresAt interface{}) *MockSessionRepository_CreateSession_Call {
	return &MockSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, data, expiresAt)}
}

func (_c *MockSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, data map[string]any, expiresAt time.Time)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(map[string]any), args[3].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) Return(sessionModel *snowdrop.SessionModel, err error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(sessionModel, err)
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, data map[string]any, expiresAt time.Time) (*snowdrop.SessionModel, error)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredSessions provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteExpiredSessions(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_DeleteExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredSessions'
type MockSessionRepository_DeleteExpiredSessions_Call struct {
	*mock.Call
}

// DeleteExpiredSessions is a helper method to define mock.On call
//   - ctx
func (_e *MockSessionRepository_Expecter) DeleteExpiredSessions(ctx interface{}) *MockSessionRepository_DeleteExpiredSessions_Call {
	return &MockSessionRepository_DeleteExpiredSessions_Call{Call: _e.mock.On("DeleteExpiredSessions", ctx)}
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Run(run func(ctx context.Context)) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Return(err error) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) RunAndReturn(run func(ctx context.Context) error) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteSession(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx
//   - sessionID
func (_e *MockSessionRepository_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockSessionRepository_DeleteSession_Call {
	return &MockSessionRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockSessionRepository_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) Return(err error) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) GetSession(ctx context.Context, sessionID string) (*snowdrop.SessionModel, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *snowdrop.SessionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snowdrop.SessionModel, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snowdrop.SessionModel); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowdrop.SessionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx
//   - sessionID
func (_e *MockSessionRepository_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockSessionRepository_GetSession_Call {
	return &MockSessionRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockSessionRepository_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_GetSession_Call) Return(sessionModel *snowdrop.SessionModel, err error) *MockSessionRepository_GetSession_Call {
	_c.Call.Return(sessionModel, err)
	return _c
}

func (_c *MockSessionRepository_GetSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*snowdrop.SessionModel, error)) *MockSessionRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateSession(ctx context.Context, sessionID string, lastAccessedAt time.Time, expiresAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, lastAccessedAt, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, lastAccessedAt, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type MockSessionRepository_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx
//   - sessionID
//   - lastAccessedAt
//   - expiresAt
func (_e *MockSessionRepository_Expecter) UpdateSession(ctx interface{}, sessionID interface{}, lastAccessedAt interface{}, expiresAt interface{}) *MockSessionRepository_UpdateSession_Call {
	return &MockSessionRepository_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, sessionID, lastAccessedAt, expiresAt)}
}

func (_c *MockSessionRepository_UpdateSession_Call) Run(run func(ctx context.Context, sessionID string, lastAccessedAt time.Time, expiresAt time.Time)) *MockSessionRepository_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepository_UpdateSession_Call) Return(err error) *MockSessionRepository_UpdateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, lastAccessedAt time.Time, expiresAt time.Time) error) *MockSessionRepository_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}
