// Code generated by mockery. DO NOT EDIT.

package mocksnowdrop

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	snowdrop "internal.snowdrop/framework"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, userID, expiresAt
func (_m *MockSessionRepository) CreateSession(ctx context.Context, userID uuid.UUID, expiresAt time.Time) (*snowdrop.SessionModel, error) {
	ret := _m.Called(ctx, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *snowdrop.SessionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (*snowdrop.SessionModel, error)); ok {
		return rf(ctx, userID, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) *snowdrop.SessionModel); ok {
		r0 = rf(ctx, userID, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowdrop.SessionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - expiresAt time.Time
func (_e *MockSessionRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, expiresAt interface{}) *MockSessionRepository_CreateSession_Call {
	return &MockSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, expiresAt)}
}

func (_c *MockSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, expiresAt time.Time)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) Return(_a0 *snowdrop.SessionModel, _a1 error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (*snowdrop.SessionModel, error)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredSessions provides a mock function with given fields: ctx
func (_m *MockSessionRepository) DeleteExpiredSessions(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_DeleteExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredSessions'
type MockSessionRepository_DeleteExpiredSessions_Call struct {
	*mock.Call
}

// DeleteExpiredSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionRepository_Expecter) DeleteExpiredSessions(ctx interface{}) *MockSessionRepository_DeleteExpiredSessions_Call {
	return &MockSessionRepository_DeleteExpiredSessions_Call{Call: _e.mock.On("DeleteExpiredSessions", ctx)}
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Run(run func(ctx context.Context)) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Return(_a0 error) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) RunAndReturn(run func(context.Context) error) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, sessionID
func (_m *MockSessionRepository) DeleteSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionRepository_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockSessionRepository_DeleteSession_Call {
	return &MockSessionRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockSessionRepository_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) Return(_a0 error) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, sessionID
func (_m *MockSessionRepository) GetSession(ctx context.Context, sessionID string) (*snowdrop.SessionModel, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *snowdrop.SessionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*snowdrop.SessionModel, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *snowdrop.SessionModel); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowdrop.SessionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionRepository_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockSessionRepository_GetSession_Call {
	return &MockSessionRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockSessionRepository_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_GetSession_Call) Return(_a0 *snowdrop.SessionModel, _a1 error) *MockSessionRepository_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_GetSession_Call) RunAndReturn(run func(context.Context, string) (*snowdrop.SessionModel, error)) *MockSessionRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function with given fields: ctx, sessionID, lastAccessedAt, expiresAt
func (_m *MockSessionRepository) UpdateSession(ctx context.Context, sessionID string, lastAccessedAt time.Time, expiresAt time.Time) error {
	ret := _m.Called(ctx, sessionID, lastAccessedAt, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, sessionID, lastAccessedAt, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type MockSessionRepository_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - lastAccessedAt time.Time
//   - expiresAt time.Time
func (_e *MockSessionRepository_Expecter) UpdateSession(ctx interface{}, sessionID interface{}, lastAccessedAt interface{}, expiresAt interface{}) *MockSessionRepository_UpdateSession_Call {
	return &MockSessionRepository_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, sessionID, lastAccessedAt, expiresAt)}
}

func (_c *MockSessionRepository_UpdateSession_Call) Run(run func(ctx context.Context, sessionID string, lastAccessedAt time.Time, expiresAt time.Time)) *MockSessionRepository_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepository_UpdateSession_Call) Return(_a0 error) *MockSessionRepository_UpdateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_UpdateSession_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) error) *MockSessionRepository_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
