// Code generated by mockery. DO NOT EDIT.

package mockweb

import (
	mock "github.com/stretchr/testify/mock"
	web "internal.snowdrop/common/core/web"
)

// MockBinderOptFn is an autogenerated mock type for the BinderOptFn type
type MockBinderOptFn struct {
	mock.Mock
}

type MockBinderOptFn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBinderOptFn) EXPECT() *MockBinderOptFn_Expecter {
	return &MockBinderOptFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockBinderOptFn) Execute(_a0 *web.Binder) {
	_m.Called(_a0)
}

// MockBinderOptFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockBinderOptFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *web.Binder
func (_e *MockBinderOptFn_Expecter) Execute(_a0 interface{}) *MockBinderOptFn_Execute_Call {
	return &MockBinderOptFn_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockBinderOptFn_Execute_Call) Run(run func(_a0 *web.Binder)) *MockBinderOptFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*web.Binder))
	})
	return _c
}

func (_c *MockBinderOptFn_Execute_Call) Return() *MockBinderOptFn_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBinderOptFn_Execute_Call) RunAndReturn(run func(*web.Binder)) *MockBinderOptFn_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockBinderOptFn creates a new instance of MockBinderOptFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBinderOptFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBinderOptFn {
	mock := &MockBinderOptFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
