// Code generated by mockery. DO NOT EDIT.

package mockweb

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
	web "internal.snowdrop/common/core/web"
)

// MockHTTPHandler is an autogenerated mock type for the HTTPHandler type
type MockHTTPHandler struct {
	mock.Mock
}

type MockHTTPHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPHandler) EXPECT() *MockHTTPHandler_Expecter {
	return &MockHTTPHandler_Expecter{mock: &_m.Mock}
}

// Method provides a mock function with no fields
func (_m *MockHTTPHandler) Method() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHTTPHandler_Method_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Method'
type MockHTTPHandler_Method_Call struct {
	*mock.Call
}

// Method is a helper method to define mock.On call
func (_e *MockHTTPHandler_Expecter) Method() *MockHTTPHandler_Method_Call {
	return &MockHTTPHandler_Method_Call{Call: _e.mock.On("Method")}
}

func (_c *MockHTTPHandler_Method_Call) Run(run func()) *MockHTTPHandler_Method_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPHandler_Method_Call) Return(_a0 string) *MockHTTPHandler_Method_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPHandler_Method_Call) RunAndReturn(run func() string) *MockHTTPHandler_Method_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function with no fields
func (_m *MockHTTPHandler) Path() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHTTPHandler_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockHTTPHandler_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockHTTPHandler_Expecter) Path() *MockHTTPHandler_Path_Call {
	return &MockHTTPHandler_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockHTTPHandler_Path_Call) Run(run func()) *MockHTTPHandler_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPHandler_Path_Call) Return(_a0 string) *MockHTTPHandler_Path_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPHandler_Path_Call) RunAndReturn(run func() string) *MockHTTPHandler_Path_Call {
	_c.Call.Return(run)
	return _c
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *MockHTTPHandler) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// MockHTTPHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockHTTPHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *MockHTTPHandler_Expecter) ServeHTTP(_a0 interface{}, _a1 interface{}) *MockHTTPHandler_ServeHTTP_Call {
	return &MockHTTPHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", _a0, _a1)}
}

func (_c *MockHTTPHandler_ServeHTTP_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *MockHTTPHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockHTTPHandler_ServeHTTP_Call) Return() *MockHTTPHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPHandler_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockHTTPHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}

// Tags provides a mock function with no fields
func (_m *MockHTTPHandler) Tags() []web.RouteTag {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 []web.RouteTag
	if rf, ok := ret.Get(0).(func() []web.RouteTag); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]web.RouteTag)
		}
	}

	return r0
}

// MockHTTPHandler_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type MockHTTPHandler_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
func (_e *MockHTTPHandler_Expecter) Tags() *MockHTTPHandler_Tags_Call {
	return &MockHTTPHandler_Tags_Call{Call: _e.mock.On("Tags")}
}

func (_c *MockHTTPHandler_Tags_Call) Run(run func()) *MockHTTPHandler_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPHandler_Tags_Call) Return(_a0 []web.RouteTag) *MockHTTPHandler_Tags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPHandler_Tags_Call) RunAndReturn(run func() []web.RouteTag) *MockHTTPHandler_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPHandler creates a new instance of MockHTTPHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPHandler {
	mock := &MockHTTPHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
