---
name: lms

volumes:
  postgres-data:

networks:
  backend:

configs:
  pgpass:
    content: ${MOVIE_DB_ADMIN_PASSWORD}
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "${MOVIE_DB_NAME}",
            "Host": "database",
            "Port": 5432,
            "MaintenanceDB": "${MOVIE_DB_NAME}",
            "Username": "${MOVIE_DB_ADMIN_USER}",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          }
        }
      }

services:
  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${MOVIE_DB_NAME}
      DB_USER: ${MOVIE_DB_ADMIN_USER}
      DB_PASSWORD: ${MOVIE_DB_ADMIN_PASSWORD}
    networks:
      - backend

  database:
    container_name: database
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_SUPER_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_DB_PASSWORD}
      MOVIE_DB_NAME: ${MOVIE_DB_NAME}
      MOVIE_DB_ADMIN_USER: ${MOVIE_DB_ADMIN_USER}
      MOVIE_DB_ADMIN_PASSWORD: ${MOVIE_DB_ADMIN_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.docker/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: Keep!t5ecret
    ports:
      - 8080:80
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    networks:
      - backend
