// Code generated by mockery. DO NOT EDIT.

package mockusermgt

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	usermgt "internal.snowdrop/common/features/usermgt"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, createUserDTO
func (_m *MockUserService) CreateUser(ctx context.Context, createUserDTO usermgt.CreateUserDTO) (*usermgt.UserDTO, error) {
	ret := _m.Called(ctx, createUserDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *usermgt.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermgt.CreateUserDTO) (*usermgt.UserDTO, error)); ok {
		return rf(ctx, createUserDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermgt.CreateUserDTO) *usermgt.UserDTO); ok {
		r0 = rf(ctx, createUserDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usermgt.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermgt.CreateUserDTO) error); ok {
		r1 = rf(ctx, createUserDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - createUserDTO usermgt.CreateUserDTO
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, createUserDTO interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, createUserDTO)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, createUserDTO usermgt.CreateUserDTO)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermgt.CreateUserDTO))
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(_a0 *usermgt.UserDTO, _a1 error) *MockUserService_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(context.Context, usermgt.CreateUserDTO) (*usermgt.UserDTO, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockUserService) Login(ctx context.Context, username string, password string) (*usermgt.UserDTO, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *usermgt.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*usermgt.UserDTO, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *usermgt.UserDTO); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usermgt.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockUserService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockUserService_Login_Call {
	return &MockUserService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockUserService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_Login_Call) Return(_a0 *usermgt.UserDTO, _a1 error) *MockUserService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Login_Call) RunAndReturn(run func(context.Context, string, string) (*usermgt.UserDTO, error)) *MockUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// NewMockUserService creates and returns a new instance of MockUserService for testing.
// 
// It initializes the mock, registers it with the provided testing interface, and sets up a
// cleanup callback to automatically assert that all expected mock interactions occurred at
// the end of the test. The parameter 't' is typically a *testing.T instance.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
