// Code generated by mockery. DO NOT EDIT.

package mockusermgt

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	usermgt "internal.snowdrop/common/features/usermgt"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, setter
func (_m *MockUserRepository) CreateUser(ctx context.Context, setter usermgt.UserSetter) (*usermgt.UserModel, error) {
	ret := _m.Called(ctx, setter)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *usermgt.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermgt.UserSetter) (*usermgt.UserModel, error)); ok {
		return rf(ctx, setter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermgt.UserSetter) *usermgt.UserModel); ok {
		r0 = rf(ctx, setter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usermgt.UserModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermgt.UserSetter) error); ok {
		r1 = rf(ctx, setter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - setter usermgt.UserSetter
func (_e *MockUserRepository_Expecter) CreateUser(ctx interface{}, setter interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, setter)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(ctx context.Context, setter usermgt.UserSetter)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermgt.UserSetter))
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(_a0 *usermgt.UserModel, _a1 error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, usermgt.UserSetter) (*usermgt.UserModel, error)) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
