---
name: Backend

"on":
  pull_request:
    paths: [backend/**]
  push:
    paths: [backend/**]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:
  verify:
    name: Verification
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        dir: [backend]
        module: [common, console, testing, framework/snowdrop]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.work
          cache-dependency-path: backend/**/*.sum
      - name: Verify dependencies
        working-directory: ${{ matrix.dir }}/${{ matrix.module }}
        run: |
          go mod tidy || {
            echo "go mod tidy failed."
            exit 1
          }

          go work sync || {
            echo "go work sync failed."
            exit 1
          }

          git diff --exit-code --quiet go.mod go.sum "$(go env GOWORK)" "$(go env GOWORK).sum" || {
            echo "git diff failed."
            exit 1
          }

          echo "go mod tidy succeeded."
      - name: Generate and verify mocks
        if: ${{ matrix.module == 'testing' }}
        working-directory: ${{ matrix.dir }}/${{ matrix.module }}
        run: |
          rm -rf mocks
          go tool mockery

          git diff --exit-code || {
            echo "⚠️ Mock files are out of date. Please run 'go tool mockery' locally and commit the changes."
            exit 1
          }
      - name: Run golangci-linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
        with:
          version: v2.1.6
          problem-matchers: true
          working-directory: ${{ matrix.dir }}/${{ matrix.module }}
          args: --output.sarif.path ${{ matrix.module }}/report.sarif
      - name: Upload report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ matrix.dir }}/${{ matrix.module }}/report.sarif
          wait-for-processing: true

  unit-test:
    name: Unit test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.work
          cache-dependency-path: backend/testing/go.sum
      - name: Unit test
        working-directory: backend/testing
        run: |
          go tool ginkgo run \
            --keep-going \
            --randomize-all \
            --randomize-suites \
            --procs=4 \
            --label-filter="!integration" \
            --require-suite \
            --trace \
            --github-output \
            --junit-report="junit.xml" \
            --race \
            --cover \
            --covermode="atomic" \
            --coverpkg="internal.snowdrop/common/...,internal.snowdrop/console/...,internal.snowdrop/framework/..." \
            --coverprofile="coverage.txt" \
            --output-dir="./reports/unit-test" \
            -r
      - name: Integration test
        working-directory: backend/testing
        run: |
          go tool ginkgo run \
            --keep-going \
            --randomize-all \
            --randomize-suites \
            --label-filter="integration" \
            --require-suite \
            --trace \
            --github-output \
            --junit-report="junit.xml" \
            --race \
            --cover \
            --covermode="atomic" \
            --coverpkg="internal.snowdrop/common/...,internal.snowdrop/console/...,internal.snowdrop/framework/..." \
            --coverprofile="coverage.txt" \
            --output-dir="./reports/integration-test" \
            -r
      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          directory: backend/testing/reports
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          directory: backend/testing/reports

  build:
    name: Build image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.work
          cache-dependency-path: backend/**/*.sum
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - name: Build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: backend
          file: backend/console/Dockerfile
          load: true
          push: false
          tags: internal.snowdrop/app:0.0.1-dev
