---
name: SQL Linter

"on":
  pull_request:
    branches: [main]
    paths: ["**/*.sql"]
  push:
    branches: [main]
    paths: ["**/*.sql"]
  schedule:
    - cron: 0 0 1 * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  sqlfluff:
    name: Check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install SQLFluff
        run: pip install sqlfluff==3.3.1
      - name: Lint ./*.sql
        run: sqlfluff lint --dialect postgres .
